name: EasyShearing
version: '1.4.1'
main: me.grovre.easyshearing.EasyShearing
api-version: 1.20
authors: [ PoptartFromPluto ]
description: Shears all animals of that type in a 5 block radius
website: https://github.com/grovre
